from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 595)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 781, 561))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 49, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame)
        self.groupBox.setGeometry(QtCore.QRect(150, 100, 501, 341))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.idFactura = QtWidgets.QLabel(parent=self.frame_2)
        self.idFactura.setObjectName("idFactura")
        self.horizontalLayout.addWidget(self.idFactura)
        self.verticalLayout.addWidget(self.frame_2)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.fechaFactura = QtWidgets.QLabel(parent=self.groupBox)
        self.fechaFactura.setObjectName("fechaFactura")
        self.verticalLayout.addWidget(self.fechaFactura)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.montoFactura = QtWidgets.QLabel(parent=self.groupBox)
        self.montoFactura.setObjectName("montoFactura")
        self.verticalLayout.addWidget(self.montoFactura)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.productos = QtWidgets.QLabel(parent=self.groupBox)
        self.productos.setObjectName("productos")
        self.verticalLayout.addWidget(self.productos)
        self.clienteActual = QtWidgets.QLabel(parent=self.frame)
        self.clienteActual.setGeometry(QtCore.QRect(70, 20, 49, 16))
        self.clienteActual.setObjectName("clienteActual")
        self.idClienteActual = QtWidgets.QLabel(parent=self.frame)
        self.idClienteActual.setGeometry(QtCore.QRect(70, 40, 49, 16))
        self.idClienteActual.setObjectName("idClienteActual")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Cliente:"))
        self.label_2.setText(_translate("MainWindow", "Id:"))
        self.groupBox.setTitle(_translate("MainWindow", "Factura"))
        self.label_3.setText(_translate("MainWindow", "Factura Id:"))
        self.idFactura.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Fecha:"))
        self.fechaFactura.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "Monto:"))
        self.montoFactura.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "Productos"))
        self.productos.setText(_translate("MainWindow", "TextLabel"))
        self.clienteActual.setText(_translate("MainWindow", "TextLabel"))
        self.idClienteActual.setText(_translate("MainWindow", "TextLabel"))
